version: '3.8'

services:

  symfony-installer:
    image: aurelienandre/symfony-installer:latest
    command: new --full lts
    environment:
      EMAIL: your@mail.fr
    volumes:
      - ./src:/app:rw,delegated
